##########################################################
# Created by: rtarkunde                                  #
# Created on: Wednesday 30 November 2022 09:56:05 AM IST #
##########################################################


SRCDIR = ../src
INCLUDEDIR = ../include
OBJDIR = ../obj
BINDIR = ../bin
CFLAGS = -c -g -Wall -I${INCLUDEDIR}




all:

	gcc ${CFLAGS}  ${SRCDIR}/main.c -o ${OBJDIR}/main.o
	gcc ${OBJDIR}/main.o -o ${BINDIR}/simpleLinkList.bin


clean:

	rm ${OBJDIR}/main.o ${BINDIR}/simpleLinkList.bin


#################### End of Makefile #####################
